FSaleAdmin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FSale.Models;
using RestSharp;
using System.Net.Http;
using System.Threading.Tasks;

namespace FSale.Controllers
{

    public class HomeController : Controller
    {
        // GET: Home
        [SessionAuthorizeAttribute]
        public ActionResult Index()
        {
            ViewBag.ActiveMenu = 0;
            return View();
        }
        [SessionAuthorizeAttribute]
        public ActionResult Category()
        {
            ViewBag.ActiveMenu = 1;
            return View();
        }
        [SessionAuthorizeAttribute]
        public ActionResult Products()
        {
            ViewBag.ActiveMenu = 1;
            return View();
        }
        [SessionAuthorizeAttribute]
        public ActionResult Customers()
        {
            ViewBag.ActiveMenu = 3;
            return View();
        }
        [SessionAuthorizeAttribute]
        public ActionResult Prices()
        {
            ViewBag.ActiveMenu = 1;
            return View();
        }
        [SessionAuthorizeAttribute]
        public ActionResult Vendors()
        {
            ViewBag.ActiveMenu = 3;
            return View();
        }
        [SessionAuthorizeAttribute]
        public ActionResult DeliveryVendors()
        {
            ViewBag.ActiveMenu = 3;
            return View();
        }
        [SessionAuthorizeAttribute]
        public ActionResult Imports()
        {
            ViewBag.ActiveMenu = 2;
            ViewBag.EmployeeId = Session["EmployeeId"].ToString();
            ViewBag.BranchId = Session["BranchId"].ToString();
            return View();
        }
        [SessionAuthorizeAttribute]
        public ActionResult Cashes()
        {
            ViewBag.ActiveMenu = 4;
            return View();
        }
        [SessionAuthorizeAttribute]
        public ActionResult Debts()
        {
            ViewBag.ActiveMenu = 4;
            return View();
        }

        [SessionAuthorizeAttribute]
        public ActionResult Exims()
        {
            ViewBag.ActiveMenu = 2;
            return View();
        }

        [SessionAuthorizeAttribute]
        public ActionResult Orders()
        {
            ViewBag.ActiveMenu = 2;
            return View();
        }

        [SessionAuthorizeAttribute]
        public ActionResult Returns()
        {
            ViewBag.ActiveMenu = 2;
            ViewBag.EmployeeId = Session["EmployeeId"].ToString();
            ViewBag.BranchId = Session["BranchId"].ToString();
            return View();
        }

        [SessionAuthorizeAttribute]
        public ActionResult Employees()
        {
            ViewBag.ActiveMenu = -1;
            ViewBag.GroupEployee = Session["Group"].ToString();
            return View();
        }

        //Add by Phung The Nhan
        [SessionAuthorizeAttribute]
        public ActionResult Actions()
        {
            ViewBag.ActiveMenu = 0;
            //ViewBag.EmployeeId = Session["EmployeeId"].ToString();
            //ViewBag.BranchId = Session["BranchId"].ToString();
            return View();
        }
        [SessionAuthorizeAttribute]
        public ActionResult DetailAction(string type, int id)
        {
            ViewBag.ActiveMenu = 0;
            ViewBag.TypeAction = type;
            ViewBag.DetailActionId = id;
            return View();
        }

        [SessionAuthorizeAttribute]
        public ActionResult CMSadmin()
        {
            ViewBag.ActiveMenu = 1;
            return View();
        }

        public ActionResult Logout()
        {
            Session["EmployeeId"] = null;
            Session["ShopId"] = null;
            Session["UserId"] = null;
            Session["EmployeeName"] = null;
            Session["BranchId"] = null;
            Session["FacebookUserToken"] = null;
            Session["access_token"] = null;
            Session["temp_Email"] = null;
            Session["temp_Password"] = null;
            Session["IsTokenValid"] = null;
            Session["isNewUser"] = null;
            Session["FacebookUserId"] = null;
            Session["Group"] = null;
            return Redirect(Request.Url.Scheme + "://" + Request.Url.Host);
        }

        [SessionAuthorizeAttribute]
        public ActionResult Sales()
        {
            ViewBag.EmployeeId = Session["EmployeeId"].ToString();
            ViewBag.BranchId = Session["BranchId"].ToString();
            ViewBag.ActiveMenu = 10;
            return View();
        }

        [SessionAuthorizeAttribute]
        public ActionResult Transfers()
        {
            ViewBag.ActiveMenu = 2;
            ViewBag.EmployeeId = Session["EmployeeId"].ToString();
            ViewBag.BranchId = Session["BranchId"].ToString();
            return View();
        }

        [SessionAuthorizeAttribute]
        public ActionResult Branches()
        {
            ViewBag.ActiveMenu = -1;
            return View();
        }

        [SessionAuthorizeAttribute]
        public ActionResult Pages()
        {
            ViewBag.Group = Session["Group"] != null ? "'" + Session["Group"].ToString() + "'" : "''";
            ViewBag.FacebookUserId = Session["FacebookUserId"] != null ? "'" + Session["FacebookUserId"].ToString() + "'" : "''";
            ViewBag.ActiveMenu = -1;
            return View();
        }

        [SessionAuthorizeAttribute]
        public ActionResult ReportEveryDay()
        {
            ViewBag.ActiveMenu = 5;
            ViewBag.BranchId = Session["BranchId"].ToString();
            return View();
        }

        [SessionAuthorizeAttribute]
        public ActionResult ReportSale()
        {
            ViewBag.ActiveMenu = 5;
            ViewBag.BranchId = Session["BranchId"].ToString();
            return View();
        }

        [SessionAuthorizeAttribute]
        public ActionResult ReportSales()
        {
            ViewBag.ActiveMenu = 5;
            ViewBag.BranchId = Session["BranchId"].ToString();
            return View();
        }

        [SessionAuthorizeAttribute]
        public ActionResult ReportCashes()
        {
            ViewBag.ActiveMenu = 5;
            ViewBag.BranchId = Session["BranchId"].ToString();
            return View();
        }

        [SessionAuthorizeAttribute]
        public ActionResult ReportOrder()
        {
            ViewBag.ActiveMenu = 5;
            ViewBag.BranchId = Session["BranchId"].ToString();
            return View();
        }

        [SessionAuthorizeAttribute]
        public ActionResult ReportProduct()
        {
            ViewBag.ActiveMenu = 5;
            ViewBag.BranchId = Session["BranchId"].ToString();
            return View();
        }

        [SessionAuthorizeAttribute]
        public ActionResult ReportCustomer()
        {
            ViewBag.ActiveMenu = 5;
            ViewBag.BranchId = Session["BranchId"].ToString();
            return View();
        }

        [SessionAuthorizeAttribute]
        public ActionResult ReportVendor()
        {
            ViewBag.ActiveMenu = 5;
            ViewBag.BranchId = Session["BranchId"].ToString();
            return View();
        }

        [SessionAuthorizeAttribute]
        public ActionResult ReportEmployees()
        {
            ViewBag.ActiveMenu = 5;
            ViewBag.BranchId = Session["BranchId"].ToString();
            return View();
        }

        [SessionAuthorizeAttribute]
        public ActionResult ReportFinance()
        {
            ViewBag.ActiveMenu = 5;
            ViewBag.BranchId = Session["BranchId"].ToString();
            return View();
        }

        public ActionResult Chat()
        {
            //
            DateTime now = DateTime.Now;
            int unix = (int)now.Subtract(new DateTime(1970, 1, 1)).TotalSeconds;
            string input = "fb.sale|" + Session["temp_Email"].ToString() + "|" + Session["temp_Password"].ToString() + "|" + unix;
            string hash = Security.Encrypt("fbsale@!321", input);
            hash = HttpUtility.UrlEncode(hash);
            return Redirect("http://chat.fb.sale?hash=" + hash + "&time=" + unix);
        }

        [SessionAuthorizeAttribute]
        public ActionResult CustomerReturns()
        {
            ViewBag.ActiveMenu = 2;
            return View();
        }

        [SessionAuthorizeAttribute]
        public ActionResult BranchTransfers()
        {
            ViewBag.ActiveMenu = 2;
            return View();
        }
        public ActionResult Error()
        {
            return View();
        }

        [SessionAuthorizeAttribute]
        public ActionResult ImportReturns(string code)
        {
            ViewBag.ActiveMenu = 2;
            ViewBag.EmployeeId = Session["EmployeeId"].ToString();
            ViewBag.BranchId = Session["BranchId"].ToString();
            ViewBag.EximCode = "'" + code + "'";
            return View();
        }

        [SessionAuthorizeAttribute]
        public ActionResult VendorReturns()
        {
            ViewBag.ActiveMenu = 2;
            return View();
        }


    }
}

FSaleAdmin/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FSale.Controllers
{
    public class SharedController : Controller
    {
        public PartialViewResult BoxRecentAction()
        {
            return PartialView();
        }
        public PartialViewResult BoxLogin()
        {
            return PartialView();
        }

        public ActionResult ErrorPage()
        {
            return View();
        }
    }
}

FSaleAdmin/Views/Home/BranchTransfers.cshtml
@{
    Layout = "~/Views/Shared/_HomeShared.cshtml";
    ViewBag.Title = "FB.SALE - Quản lý đơn hàng";
}

<div ng-controller="BranchTransfersController" ng-init="init();">
    <div>
        <div class="breadcrumb-main left w100pt">
            <div class="row">
                <div class="col-sm-9">
                    <h2><i class="fa fa-th" aria-hidden="true"></i> Quản lý chuyển hàng </h2>
                    <a href="/transfers.html" class="addPro"><i class="fa fa-plus" aria-hidden="true"></i> Chuyển hàng</a>
                    <a href="#" class="hidden"><i class="fa fa-sign-in" aria-hidden="true"></i>Nhập file</a>
                    <a href="#" class="hidden"><i class="fa fa-sign-out" aria-hidden="true"></i> Xuất file</a>
                </div>
            </div>
        </div>
        <div class="box-store-list left w100pt">
            <div class="table-list w100pt left">
                <table id="report" class="table table-responsive">
                    <tr>
                        <th>STT</th>
                        <th>Mã</th>
                        <th>Thời gian</th>
                        <th>Từ chi nhánh</th>
                        <th>Đến chi nhánh</th>
                        <th>Giá trị chuyển</th>
                    </tr>
                    <tr ng-class-odd="'arrow odd'" ng-class-even="'arrow odd bge'" ng-class="{up: transfer.isExpand}" ng-repeat-start=" transfer in transfers" ng-click="expandDetail(transfer);">
                        <td><b>{{((page-1) * page_size) + $index + 1}}</b></td>
                        <td>{{ transfer.Code }}</td>
                        <td>{{ transfer.CreatedAt | date : "dd/MM/yyyy" }}</td>
                        <td>{{ transfer.fromBranch.BranchName }}</td>
                        <td>{{ transfer.toBranch.BranchName }}</td>
                        <td>{{ transfer.Total | formatPrice }}</td>
                    </tr>
                    <tr class="t-content" ng-repeat-end ng-show="transfer.isExpand">
                        <td colspan="20" class="">
                            <div class="left w100pt info-product">
                                <!-- Nav tabs -->
                                <uib-tabset active="active">
                                    <uib-tab index="0" heading="Thông tin">
                                        <div class="info-product-right left">
                                            <div class="col-lg-6 info-product-tt">
                                                <ul>
                                                    <li><span class="txt-left">Mã phiếu:</span> {{ transfer.Code}}</li>
                                                    <li><span class="txt-left">Thời gian :</span> {{ transfer.CreatedAt | date : "dd/MM/yyyy HH:mm:ss" }}</li>
                                                    <li><span class="txt-left">Người tạo :</span><p> {{  transfer.employee.EmployeeName }}</p></li>
                                                    <li style="border-bottom:0;"><span class="txt-left">Ghi chú :</span> <textarea ng-model="transfer.Note"></textarea></li>
                                                </ul>
                                            </div>
                                            <div class="col-lg-6 info-product-tt last">
                                                <ul>
                                                    <li><span class="txt-left">Từ chi nhánh :</span><p>{{ transfer.fromBranch.BranchName }}</p></li>
                                                    <li><span class="txt-left">Đến chi nhánh :</span><p>{{ transfer.toBranch.BranchName }}</p></li>
                                                    <li><span class="txt-left">Trạng thái :</span> {{ transfer.Status == 2 | iif : "Hoàn thành" : "Chưa hoàn thành"  }}</li>
                                                </ul>
                                            </div>
                                            <div class="table-othe">
                                                <table class="table">
                                                    <thead>
                                                        <tr class="success">
                                                            <th align="left">Mã hàng hóa</th>
                                                            <th align="left">Tên hàng hóa</th>
                                                            <th align="left">Đơn giá</th>
                                                            <th align="left">Số lượng</th>
                                                            <th align="right">Thành tiền</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <tr ng-repeat="product in transfer.products">
                                                            <td align="left">{{ product.ProductCode }}</td>
                                                            <td><a href="#"><b>{{ product.ProductName }}<br />{{ product.SubName }}</b></a></td>
                                                            <td align="right">{{ product.Price | formatPrice }}</td>
                                                            <td align="right">{{ product.Quantity }}</td>
                                                            <td align="right">{{ product.TotalPrice | formatPrice }}</td>
                                                        </tr>
                                                        <tr class="sum-bill-price">
                                                            <td align="right" colspan="4">Tổng tiền hàng:</td>
                                                            <td align="right"><b>{{  transfer.Total | formatPrice }}</b></td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                            <div class="clearfix"></div>
                                            <button type="button" class="btn btn-default" ng-click="updateTransfer(transfer)">
                                                <i class="fa fa-check-square-o" style="color:#666" aria-hidden="true"></i> Lưu
                                            </button>
                                        </div>
                                    </uib-tab>
                                </uib-tabset>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="news-pagging">
                <ul uib-pagination boundary-links="true" total-items="item_count" ng-model="page" items-per-page="page_size" class="pagination-sm" previous-text="&lsaquo;" next-text="&rsaquo;" first-text="&laquo;" last-text="&raquo;" ng-change="onPageChange()" rotate ="true" max-size="10"></ul>
            </div>
        </div>
    </div>
</div>

FSaleAdmin/Views/Home/Category.cshtml
@{
    Layout = "~/Views/Shared/_HomeShared.cshtml";
    ViewBag.Title = "FB.SALE - Quản lý danh mục";
}

<div ng-controller="CategoryController">
    <div>
        <div class="breadcrumb-main left w100pt">
            <div class="row">
                <div class="col-sm-9">
                    <h2><i class="fa fa-list" aria-hidden="true"></i> Danh mục sản phẩm </h2>
                    <a href="#" class="addPro" data-toggle="modal" data-target="#cateModal"><i class="fa fa-plus" aria-hidden="true"></i>Tạo danh mục</a>
                    <a href="#" class="hidden"><i class="fa fa-sign-in" aria-hidden="true"></i>Nhập file</a>
                    <a href="#" class="hidden"><i class="fa fa-sign-out" aria-hidden="true"></i> Xuất file</a>
                </div>
                <div class="boxSearch right col-sm-3 hidden">
                    <form class="form-inline">
                        <div class="form-group form-control">
                            <input type="email" class="" id="exampleInputEmail3" placeholder="Tìm kiếm thông tin">
                            <button type="submit" class="btn btn-default">
                                <i class="fa fa-search"
                                   aria-hidden="true"></i>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!--list-categories -->
        <div class="list-categories left w100pt">
            <div class="col-sm-9">
                <div id="wrapper">
                    <div id="list" class="row item" ng-init="initCategory();">
                        <div class="item">
                            <div masonry item-selector=".list-items" preserve-order>
                                <div masonry-brick class="list-items" ng-repeat=" category in categories">
                                    <div class="title-item">
                                        <a href="#">{{ category.CategoryName +'('+category.ProductCount+')'}}</a>
                                        <button ng-click="editCategory(category);"><i class="fa fa-edit"></i> </button>
                                    </div>
                                    <ul>
                                        <li ng-repeat="childCategory in category.children" ng-class="{'clearfix': $first}">
                                            <a href="#">{{ childCategory.CategoryName }} <i>{{ childCategory.ProductCount }}</i></a>
                                            <button ng-click="editCategory(childCategory);"> <i class="fa fa-edit"></i> </button>
                                        </li>
                                    </ul>
                                </div> 
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @Html.Action("BoxRecentAction", "Shared")
        </div>
    </div>

    <div class="modal fade box-popup cateModal" id="cateModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="clip"></div>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title"><span class="fa fa-list-ul"></span>Thêm danh mục</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group row form-pad">
                        <label for="input">Tên nhóm</label>
                        <div>
                            <input type="text" class="form-control" id="txtCategoryName" maxlength="49" ng-model="newCategory.CategoryName" ng-init="newCategory.CategoryName = ''" placeholder="Nhập tên danh mục">
                            <span class="err_msg" ng-show="newCategory.CategoryName == '' || newCategory.CategoryName == undefined">*</span>
                        </div>
                    </div>
                    <div class="form-group row form-pad">
                        <label>Nhóm cha</label>
                        <div>
                            <div class="form-group">
                                <select class="form-control" id="ddlCategory" ng-model="newCategory.CategoryParentId" ng-init="newCategory.CategoryParentId = '-1'">
                                    <option value="-1">-- Lựa chọn nhóm cha --</option>
                                    <option ng-repeat=" category in categories" value="{{ category.CategoryId }}">{{ category.CategoryName }}</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">
                        <span class="fa fa-ban"></span>Hủy
                    </button>
                    <button type="button" class="btn btn-success" ng-click="createCategory();"><span class="fa fa-save"></span>Lưu</button>
                </div>
            </div>
        </div>
    </div>

    <!--Edit Modal-->
    <div class="modal fade box-popup editModal" tabindex="-1" id="editModal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="clip"></div>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title"><span class="fa fa-list-ul"></span>Sửa danh mục</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group row form-pad">
                        <label for="input">Tên nhóm</label>
                        <div>
                            <input type="text" class="form-control" ng-model="editingCategory.CategoryName" maxlength="100" placeholder="Nhập tên danh mục">
                            <span class="err_msg" ng-show="editingCategory.CategoryName == ''">*</span>
                        </div>
                    </div>
                    <div class="form-group row form-pad">
                        <label>Nhóm cha</label>
                        <div>
                            <div class="form-group">
                                <select class="form-control" id="ddlCategory" ng-model="editingCategory.CategoryParentId" ng-options="category.CategoryId as category.CategoryName for category in categories">
                                    <option value="">-- Lựa chọn nhóm cha --</option>
                                    @*<option ng-repeat=" category in categories" value="{{ category.CategoryId }}" ng-selected="category.CategoryId == editingCategory.CategoryParentId">{{ category.CategoryName }}</option>*@
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">
                        <span class="fa fa-ban"></span>Hủy
                    </button>
                    <button type="button" class="btn btn-success" ng-click="saveCategory();"><span class="fa fa-save"></span>Lưu</button>
                    <button type="button" class="btn btn-danger" ng-click="showConfirmDeleteCategory(editingCategory);"><span class="fa fa-trash"></span>Xóa</button>
                </div>
            </div>
        </div>
    </div>
</div>

FSaleAdmin/Views/Home/ReportEveryDay.cshtml
@{
    ViewBag.Title = "ReportEveryDay";
    Layout = "~/Views/Shared/_HomeShared.cshtml";
}

<div ng-controller="ReportEveryDayController" ng-init="init();">
    <div class="box-general-store left w100pt">
        <div class="left col-lg-10" id="divDoc">
            <div class="box-store-list left w100pt">
                <div class="boxfiter w100pt left">
                    @*<h2>Bộ lọc</h2>
                        <div class="col-sm-2">
                            <select class="form-control" ng-model="q.category" ng-init="q.category = '-1'" ng-change="onQueryChange()">
                                <option value="-1">Loại hàng</option>
                                <optgroup ng-repeat=" category in categories" label="{{ category.CategoryName }}">
                                    <option ng-repeat=" childCategory in category.children" value="{{ childCategory.CategoryId }}">{{ childCategory.CategoryName }}</option>
                                </optgroup>
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <select class="form-control" ng-model="q.allowsell" ng-init="q.allowsell = '-1'" ng-change="onQueryChange()">
                                <option value="-1">Tất cả</option>
                                <option value="0">Đang kinh doanh</option>
                                <option value="1">Đã ngừng kinh doanh</option>
                            </select>
                        </div>*@
                    <h2>Số bản ghi :</h2>
                    <div class="col-sm-1">
                        <select class="form-control" ng-model="page_size" ng-init="page_size = '20'" ng-change="onPageSizeChange()">
                            <option value="20">20</option>
                            <option value="50">50</option>
                            <option value="100">100</option>
                        </select>
                    </div>
                    <a class="btn btn-primary right" ng-click="printDate();"><i class="fa fa-print"></i></a>
                </div>
                <div ng-model="dateUrl" ng-include="dateUrl"></div>
            </div>
            <div class="news-pagging">
                <ul uib-pagination boundary-links="true" total-items="item_count" ng-model="page" items-per-page="page_size" class="pagination-sm" previous-text="&lsaquo;" next-text="&rsaquo;" first-text="&laquo;" last-text="&raquo;" ng-change="onPageChange()"></ul>
            </div>
        </div>

        <div id="divHTML">
            <div class="col-lg-2 box-notifile">
                <div class="lable left">
                    <h1>
                        <i class="fa fa-external-link" aria-hidden="true"></i>
                        Kiểu hiển thị
                    </h1>
                </div>
                <div class="list-notifile left" style="padding:20px;">
                    <div id="typeDoc">
                        <input type="radio" name="typeReport" id="typeReportDoc" ng-click="saleDoc();" checked="checked" /> Báo cáo
                    </div>
                </div>
                <div class="lable left">
                    <h1>
                        <i class="fa fa-bookmark-o" aria-hidden="true"></i>
                        Mối quan tâm
                    </h1>
                </div>
                <div class="list-notifile left" style="padding:20px;">
                    <input type="radio" name="dateReport" id="dateSale" ng-click="dateSale()" checked="checked" />
                    <span style="color: #333339;"> Bán hàng </span>
                    <br />
                    <input type="radio" name="dateReport" id="dateCaches" ng-click="dateCashes2()" />
                    <span style="color: #333339;"> Thu chi </span>
                    <br />
                    <input type="radio" name="dateReport" id="dateProduct" ng-click="dateProduct2()" />
                    <span style="color: #333339;"> Hàng hóa </span>
                    <br />
                    @*<input type="radio" name="dateReport" id="dateProfit" ng-click="dateProfit()" />
                        <span style="color: #333339;"> Lợi nhuận </span>
                        <br />*@
                    @*<input type="radio" name="dateReport" id="dateTotal" ng-click="dateTotal()" />
                        <span style="color: #333339;"> Tổng hợp </span>*@
                </div>
                <div class="lable left">
                    <h1>
                        <i class="fa fa-calendar" aria-hidden="true"></i>
                        Thời gian
                    </h1>
                </div>
                <div class="list-notifile left" style="padding:20px;">
                    <input type="text" class="form-control" readonly placeholder="Chọn ngày" ng-change="onQueryChange()" uib-datepicker-popup="{{DOBformat}}" ng-model="q.StartDate" is-open="DatePopup.startDate" datepicker-options="dateOptions" close-text="Đóng" clear-text="Xóa" current-text="Hôm nay">
                    <button ng-click="openDatePopup(0);" style="position: absolute; right: 20px; border: 0px; background-color: #eeeeee; margin-top: -28px; margin-right: 3px;"><i class="fa fa-calendar"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>